### ISSUE TITLE
rfq.json has hardcoded file extensions

### ISSUE THREAD

**Issue by anujdeshpande** [product-os/rfq#6]
We have a fileTypes.json and then in the rfq.json for the hardware type in question, we hardcode these extensions in files->file-type object.

**Comment by rcooke-warwick** [comment]
@anujdeshpande this is a bit of an oversight in the code - the hardcoded extensions are part of an unused function that we can remove. Also in https://github.com/product-os/rfq/blob/typescript-ify/src/index.ts we have scrapped the filetypes distinction and have just taken everything from the outputs folder. Do we want to only take certain filetypes?
